# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Burrow < Formula
  desc "Agent-native cloud CLI: deploy and operate apps on your own Kubernetes cluster through the Burrow control plane."
  homepage "https://github.com/burrow-cloud/burrow"
  version "0.14.0-rc.31"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/burrow-cloud/burrow/releases/download/v0.14.0-rc.31/burrow_0.14.0-rc.31_darwin_amd64.tar.gz"
      sha256 "574d487d052290d4c150ff527e4d6455b32613213d425c0f150b45eff4b25eb3"

      define_method(:install) do
        bin.install "burrow"
        bin.install "burrow-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/burrow-cloud/burrow/releases/download/v0.14.0-rc.31/burrow_0.14.0-rc.31_darwin_arm64.tar.gz"
      sha256 "bcd7d2d2e25a6d99fa15b8fc3bcfb64a13e9a5e6e6e277df08e7471d8950ed95"

      define_method(:install) do
        bin.install "burrow"
        bin.install "burrow-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/burrow-cloud/burrow/releases/download/v0.14.0-rc.31/burrow_0.14.0-rc.31_linux_amd64.tar.gz"
      sha256 "3099e952c22a45d7a3280e266fd1f09de41f4b9fb9d95334fd1684a225029b27"
      define_method(:install) do
        bin.install "burrow"
        bin.install "burrow-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/burrow-cloud/burrow/releases/download/v0.14.0-rc.31/burrow_0.14.0-rc.31_linux_arm64.tar.gz"
      sha256 "a1c59b4e1ce93b816b6d2ce9c3e533f7b8f4948a59c3819be867496474f60d49"
      define_method(:install) do
        bin.install "burrow"
        bin.install "burrow-agent"
      end
    end
  end

  def caveats
    <<~EOS
      `burrow` and `burrow-agent` both take effect immediately; nothing needs restarting.

      If this release changed the agent's verbs, re-run `burrow agent <tool> install` (for
      example, `burrow agent claude install`) so the wiring in your agent's configuration
      matches what the binary now does. It is idempotent, and it backs up any file it edits.
    EOS
  end
end
