# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Burrow < Formula
  desc "Agent-native cloud CLI: deploy and operate apps on your own Kubernetes cluster through the Burrow control plane."
  homepage "https://github.com/burrow-cloud/burrow"
  version "0.14.0-rc.39"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/burrow-cloud/burrow/releases/download/v0.14.0-rc.39/burrow_0.14.0-rc.39_darwin_amd64.tar.gz"
      sha256 "8c2a4e18f2dccffeaf6fe0e853854934faab753b59da2d4aa7dc58747ff530b3"

      define_method(:install) do
        bin.install "burrow"
        bin.install "burrow-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/burrow-cloud/burrow/releases/download/v0.14.0-rc.39/burrow_0.14.0-rc.39_darwin_arm64.tar.gz"
      sha256 "91a1bd35ba0a1a27ac68e8626c17a4e7d9901b2b77aa944524f8025b82bbd967"

      define_method(:install) do
        bin.install "burrow"
        bin.install "burrow-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/burrow-cloud/burrow/releases/download/v0.14.0-rc.39/burrow_0.14.0-rc.39_linux_amd64.tar.gz"
      sha256 "7d5422937ba4aebcd56bb240be774f4fec572da63c1d03a3bfbf6c2cb0666ca0"
      define_method(:install) do
        bin.install "burrow"
        bin.install "burrow-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/burrow-cloud/burrow/releases/download/v0.14.0-rc.39/burrow_0.14.0-rc.39_linux_arm64.tar.gz"
      sha256 "18269ff5a878e26d5352605e1b9fff36a2c3bfa75fc3d0c9d1d1f6c8173bc65c"
      define_method(:install) do
        bin.install "burrow"
        bin.install "burrow-agent"
      end
    end
  end

  def caveats
    <<~EOS
      `burrow` and `burrow-agent` both take effect immediately; nothing needs restarting.

      If this release changed the agent's verbs, re-run `burrow agent <tool> install` (for
      example, `burrow agent claude install`) so the wiring in your agent's configuration
      matches what the binary now does. It is idempotent, and it backs up any file it edits.
    EOS
  end
end
