# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Burrow < Formula
  desc "Agent-native cloud CLI: deploy and operate apps on your own Kubernetes cluster through the Burrow control plane."
  homepage "https://github.com/burrow-cloud/burrow"
  version "0.14.0-rc.16"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/burrow-cloud/burrow/releases/download/v0.14.0-rc.16/burrow_0.14.0-rc.16_darwin_amd64.tar.gz"
      sha256 "69a7da547cd8feabd933477d51670678ccb7961fa9515dded2cec2d42def62d3"

      define_method(:install) do
        bin.install "burrow"
        bin.install "burrow-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/burrow-cloud/burrow/releases/download/v0.14.0-rc.16/burrow_0.14.0-rc.16_darwin_arm64.tar.gz"
      sha256 "8c3f4c4ad0b98f77bf7cafc0db4bd727538c4e63ee89038e825b2308707c61f9"

      define_method(:install) do
        bin.install "burrow"
        bin.install "burrow-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/burrow-cloud/burrow/releases/download/v0.14.0-rc.16/burrow_0.14.0-rc.16_linux_amd64.tar.gz"
      sha256 "ecd4caa4bd279f15d262bcedfe437165fd9f1b769c9755de06eba04ce5a0f008"
      define_method(:install) do
        bin.install "burrow"
        bin.install "burrow-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/burrow-cloud/burrow/releases/download/v0.14.0-rc.16/burrow_0.14.0-rc.16_linux_arm64.tar.gz"
      sha256 "b959d7f87a994cb56de673c6452b7c0c624b0ab411e26967665af57a5fb83c5d"
      define_method(:install) do
        bin.install "burrow"
        bin.install "burrow-agent"
      end
    end
  end

  def caveats
    <<~EOS
      `burrow` and `burrow-agent` both take effect immediately; nothing needs restarting.

      If this release changed the agent's verbs, re-run `burrow agent <tool> install` (for
      example, `burrow agent claude install`) so the wiring in your agent's configuration
      matches what the binary now does. It is idempotent, and it backs up any file it edits.
    EOS
  end
end
